
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DemoWebservice", targetNamespace = "http://ws/", wsdlLocation = "http://dennis-pc:8080/FirstApp/DemoWebservice?wsdl")
public class DemoWebservice
    extends Service
{

    private final static URL DEMOWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException DEMOWEBSERVICE_EXCEPTION;
    private final static QName DEMOWEBSERVICE_QNAME = new QName("http://ws/", "DemoWebservice");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://dennis-pc:8080/FirstApp/DemoWebservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEMOWEBSERVICE_WSDL_LOCATION = url;
        DEMOWEBSERVICE_EXCEPTION = e;
    }

    public DemoWebservice() {
        super(__getWsdlLocation(), DEMOWEBSERVICE_QNAME);
    }

    public DemoWebservice(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEMOWEBSERVICE_QNAME, features);
    }

    public DemoWebservice(URL wsdlLocation) {
        super(wsdlLocation, DEMOWEBSERVICE_QNAME);
    }

    public DemoWebservice(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEMOWEBSERVICE_QNAME, features);
    }

    public DemoWebservice(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DemoWebservice(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExampleWs
     */
    @WebEndpoint(name = "ExampleWsPort")
    public ExampleWs getExampleWsPort() {
        return super.getPort(new QName("http://ws/", "ExampleWsPort"), ExampleWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExampleWs
     */
    @WebEndpoint(name = "ExampleWsPort")
    public ExampleWs getExampleWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "ExampleWsPort"), ExampleWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEMOWEBSERVICE_EXCEPTION!= null) {
            throw DEMOWEBSERVICE_EXCEPTION;
        }
        return DEMOWEBSERVICE_WSDL_LOCATION;
    }

}
