
package ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExampleWs", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExampleWs {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "mirrorText", targetNamespace = "http://ws/", className = "ws.MirrorText")
    @ResponseWrapper(localName = "mirrorTextResponse", targetNamespace = "http://ws/", className = "ws.MirrorTextResponse")
    @Action(input = "http://ws/ExampleWs/mirrorTextRequest", output = "http://ws/ExampleWs/mirrorTextResponse")
    public String mirrorText(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
